---
abstract: 'Extensible framework for building bots'
author:
  - 'Andrew Sterling Hanenkamp <hanenkamp@cpan.org>'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200009, CPAN::Meta::Converter version 2.110440'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Bot-Backbone
requires:
  AnyEvent: 0
  AnyEvent::XMPP::Client: 0
  AnyEvent::XMPP::Ext::Disco: 0
  AnyEvent::XMPP::Ext::MUC: 0
  Bot::Backbone::Dispatcher::Predicate::Functor: 0
  Bot::Backbone::Dispatcher::Predicate::Nesting: 0
  Carp: 0
  List::MoreUtils: 0
  List::Util: 0
  Moose: 0
  Moose::Exporter: 0
  Moose::Meta::Class: 0
  Moose::Role: 0
  Moose::Util: 0
  MooseX::Types: 0
  MooseX::Types::Moose: 0
  POE: 0
  Scalar::Util: 0
  namespace::autoclean: 0
  perl: v5.10
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Bot-Backbone
  repository: git://github.com/zostay/Bot-Backbone.git
version: 0.112400
